on:
  push:
    branches:
      - master

jobs:
  master-push:
    name: Push to master branch
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Setting up NodeJS v10
        uses: actions/setup-node@v1
          with:
            node-version: 10
      - name: Run checks
        uses: ./.github/actions/run-checks
